server:
  port: 9001

spring:
  application:
    name: microservice-consumer
  cloud:
    consul:
      discovery:
        instance-id: microservice-consumer-9001
        prefer-ip-address: true
        metadata:
          env: zs

feign:
  circuitbreaker:
    enabled: true