server:
  port: 9031

spring:
  application:
    name: microservice-sub-producer
  cloud:
    consul:
      discovery:
        instance-id: microservice-sub-producer-9031
        prefer-ip-address: true
        metadata:
          gray-tag: true