server:
  port: 9527

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: microservice-producer
          uri: lb://microservice-producer
          predicates:
            - Path=/microservice-producer/**
          filters:
            - StripPrefix=1
        - id: microservice-websocket
          uri: lb:ws://microservice-websocket
          predicates:
            - Path=/microservice-websocket/**
          filters:
            - StripPrefix=1
eureka:
  instance:
    instance-id: microservice-gateway-9527
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

