server:
  port: 9527

spring:
  application:
    name: microservice-gateway
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
        - id: microservice-consumer
          uri: lb://microservice-consumer
          predicates:
            - Path=/microservice-consumer/**
          filters:
            - StripPrefix=1
        - id: microservice-producer
          uri: lb://microservice-producer
          predicates:
            - Path=/microservice-producer/**
          filters:
            - StripPrefix=1
        - id: microservice-sub-producer
            uri: lb://microservice-sub-producer
            predicates:
              - Path=/microservice-sub-producer/**
            filters:
              - StripPrefix=1
        - id: microservice-websocket
          uri: lb:ws://microservice-websocket
          predicates:
            - Path=/microservice-websocket/**
          filters:
            - StripPrefix=1
    consul:
      discovery:
        instance-id: microservice-gateway-9527
        prefer-ip-address: true


